name: Cypress
on: [push]
jobs:
  cypress-run:  
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          build: yarn run build
          start: yarn start
          install-command: yarn
