name: Cypress
on: [push]
jobs:
  cypress-run:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          build: yarn run build
          start: yarn run develop:ci
          install-command: yarn
          record: true
          wait-on: http://localhost:3000
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
